version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Maps localhost:8080 to Nginx port 80
    environment:
      VITE_API_BASE_URL: http://localhost:5000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
